#!/bin/bash

export CONCOURSE_WORK_DIR="{{pkg.svc_data_path}}"
export CONCOURSE_TSA_WORKER_PRIVATE_KEY="{{pkg.svc_files_path}}/worker_key"
export CONCOURSE_TSA_PUBLIC_KEY="{{pkg.svc_files_path}}/tsa_host_key.pub"
{{#if bind.atc ~}}
{{#with bind.atc.first as |atc| }}
export CONCOURSE_TSA_HOST="http://{{atc.sys.ip}}:{{atc.cfg.tsa_port}}"
{{~/with}}
{{else ~}}
export CONCOURSE_TSA_HOST="{{cfg.tsa.host}}:{{cfg.tsa.port}}"
{{/if ~}}
