#!{{pkgPathFor "core/bash"}} -xe
#
exec 2>&1

# Retire the worker to gracefully kill the service
worker=$(cat "{{pkg.svc_path}}/CONCOURSE_WORKER_NAME")
rm -f "{{pkg.svc_path}}/CONCOURSE_WORKER_NAME"
exec concourse retire-worker --name $worker

